<?php

/**
 * @file
 * Defines a naked avis layout.
 */

$plugin = array(
  'title' => 'Flight Modern',
  'category' => 'Avis',
  'icon' => 'flight_modern.png',
  'theme' => 'flight_modern',
  'regions' => array(
    'top' => 'Top',
    'content' => 'Content',
    'footer_pre_1' => 'Pre Footer 1',
    'footer_pre_2' => 'Pre Footer 2',
    'footer_pre_3' => 'Pre Footer 3',
    'footer_pre_4' => 'Pre Footer 4',
    'footer' => 'Footer',
  ),
);